# Q. 3 — Practical: Observe a Scan and an Index 
BritBooks wants to inspect how SQLite finds orders for one customer.
| Column        |  Data Type |
| ------------- |:-------------:|
| order_id      | INTEGER PRIMARY KEY     |
| customer_id   | INTEGER NOT NULL    |
| amount_gbp    | REAL NOT NULL     |
| status        | TEXT NOT NULL    |

TASK:
* Create query_performance.db . 
* Create the orders table. 
* Insert 5,000 sample orders. 
* Use EXPLAIN QUERY PLAN before creating an index.
* Create an index on Run customer_id. 
* EXPLAIN QUERY PLAN again. 
* Print both query plans.

In [56]:
import sqlite3
import random 
import pandas as pd

In [ ]:
connection = sqlite3.connect("query_performance.db")
cursor = connection.cursor()
# Create and populate the table
cursor.execute("DROP TABLE IF EXISTS orders")
cursor.execute("""
    CREATE TABLE orders(
        order_id INTEGER PRIMARY KEY,
        customer_id INTEGER NOT NULL,
        amount_gbp REAL NOT NULL,
        status TEXT NOT NULL
    )
""")
import random

# Generar los datos
orders = []

for order_id in range(1, 5001):
    customer_id = random.randint(1, 1000, seed=12345)
    amount_gbp = round(random.uniform(5, 1000), 2)
    status = random.choice([
        "Pending",
        "Dispatched",
        "Confirmed",
        "Cancelled"
    ])

    orders.append((order_id, customer_id, amount_gbp, status))

cursor.executemany("""
INSERT INTO orders (order_id, customer_id, amount_gbp, status)
VALUES (?, ?, ?, ?)
""", orders)

connection.commit()

print(f"{len(orders)} registros insertados.")

query = """
SELECT order_id, amount_gbp
FROM orders
WHERE customer_id = 3
"""

5000 registros insertados.

In [58]:
# Check the plan before the index
cursor.execute(f"EXPLAIN QUERY PLAN {query}")
print("Before index:")
for row in cursor.fetchall():
    print(row)
# Check the plan after the index
#connection.close()

Before index:
(2, 0, 216, 'SCAN orders')

In [59]:
# Create the index
cursor.execute("""
CREATE INDEX idx_orders_customer_id
ON orders(customer_id)
""")
connection.commit()

In [60]:
# Check the plan after the index
cursor.execute(f"EXPLAIN QUERY PLAN {query}")
print("After index:")
for row in cursor.fetchall():
    print(row)

After index:
(3, 0, 61, 'SEARCH orders USING INDEX idx_orders_customer_id (customer_id=?)')

# Q. 4 — Practical: Filter Early 
Create an SQLite script that compares these approaches:

*Approach A:*
* Read every order. 
* Filter Dispatched rows in Python. 
* Calculate the total in Python. 

*Approach B:*
* Filter rows in SQL. 
* Calculate the total using SUM . 
* Return only the final value. 
* Print both totals and confirm that they match.

In [ ]:
# Approach A with Pandas:
all_products_df = pd.read_sql_query("""SELECT * FROM ORDERS""", connection, index_col="order_id")
all_products_df

          customer_id  amount_gbp      status
order_id
1                 365      420.05     Pending
2                 906      826.20     Pending
3                 829      155.22   Cancelled
4                 722      508.96   Cancelled
5                  77      749.88   Cancelled
...               ...         ...         ...
4996              814       42.68   Cancelled
4997              230      769.84   Cancelled
4998              386      929.12  Dispatched
4999              430      980.25   Confirmed
5000              961      313.05  Dispatched

[5000 rows x 3 columns]

In [87]:
dispatched_orders_df = all_orders_df[all_orders_df["status"]=="Dispatched"]
python_total_amount = dispatched_orders_df["amount_gbp"].sum()
python_total_amount

np.float64(650944.29)

In [ ]:
# Approach A with python standard library:
cursor.execute("""SELECT * FROM ORDERS""")
all_orders = cursor.fetchall()
all_orders

[(1, 365, 420.05, 'Pending'),
 (2, 906, 826.2, 'Pending'),
 (3, 829, 155.22, 'Cancelled'),
 (4, 722, 508.96, 'Cancelled'),
 (5, 77, 749.88, 'Cancelled'),
 (6, 252, 565.61, 'Cancelled'),
 (7, 654, 517.8, 'Pending'),
 (8, 166, 113.2, 'Confirmed'),
 (9, 831, 597.28, 'Pending'),
 (10, 170, 896.96, 'Cancelled'),
 (11, 192, 562.98, 'Pending'),
 (12, 270, 654.26, 'Pending'),
 (13, 277, 885.69, 'Cancelled'),
 (14, 199, 127.22, 'Cancelled'),
 (15, 691, 381.15, 'Dispatched'),
 (16, 781, 174.78, 'Confirmed'),
 (17, 485, 972.12, 'Pending'),
 (18, 24, 475.78, 'Dispatched'),
 (19, 158, 282.83, 'Dispatched'),
 (20, 919, 200.93, 'Cancelled'),
 (21, 529, 267.2, 'Confirmed'),
 (22, 777, 409.26, 'Dispatched'),
 (23, 90, 420.39, 'Cancelled'),
 (24, 128, 326.04, 'Dispatched'),
 (25, 88, 312.41, 'Dispatched'),
 (26, 646, 815.6, 'Dispatched'),
 (27, 567, 169.64, 'Dispatched'),
 (28, 779, 350.26, 'Confirmed'),
 (29, 806, 158.18, 'Pending'),
 (30, 233, 263.75, 'Pending'),
 (31, 577, 679.55, 'Pending'),
 (32, 339, 176.79, 'Cancelled'),
 (33, 86, 249.47, 'Pending'),
 (34, 602, 336.47, 'Pending'),
 (35, 344, 694.9, 'Confirmed'),
 (36, 143, 863.18, 'Pending'),
 (37, 767, 660.77, 'Cancelled'),
 (38, 108, 611.2, 'Pending'),
 (39, 383, 573.3, 'Confirmed'),
 (40, 689, 509.04, 'Dispatched'),
 (41, 22, 735.27, 'Confirmed'),
 (42, 968, 294.38, 'Confirmed'),
 (43, 432, 522.36, 'Dispatched'),
 (44, 3, 118.75, 'Confirmed'),
 (45, 332, 516.7, 'Confirmed'),
 (46, 361, 402.43, 'Dispatched'),
 (47, 979, 211.01, 'Dispatched'),
 (48, 830, 350.53, 'Pending'),
 (49, 605, 140.28, 'Pending'),
 (50, 575, 421.66, 'Dispatched'),
 (51, 877, 963.66, 'Cancelled'),
 (52, 848, 826.18, 'Cancelled'),
 (53, 580, 325.22, 'Dispatched'),
 (54, 721, 556.01, 'Cancelled'),
 (55, 631, 855.1, 'Cancelled'),
 (56, 90, 50.11, 'Confirmed'),
 (57, 720, 432.28, 'Confirmed'),
 (58, 729, 705.57, 'Pending'),
 (59, 973, 154.87, 'Pending'),
 (60, 812, 992.64, 'Cancelled'),
 (61, 990, 485.11, 'Confirmed'),
 (62, 964, 604.31, 'Dispatched'),
 (63, 629, 83.47, 'Cancelled'),
 (64, 630, 30.2, 'Dispatched'),
 (65, 924, 108.26, 'Dispatched'),
 (66, 614, 163.66, 'Pending'),
 (67, 773, 394.66, 'Dispatched'),
 (68, 751, 334.63, 'Cancelled'),
 (69, 227, 69.42, 'Confirmed'),
 (70, 864, 945.86, 'Cancelled'),
 (71, 952, 196.19, 'Dispatched'),
 (72, 854, 155.28, 'Cancelled'),
 (73, 448, 5.57, 'Confirmed'),
 (74, 29, 875.89, 'Cancelled'),
 (75, 609, 913.93, 'Cancelled'),
 (76, 687, 431.73, 'Confirmed'),
 (77, 61, 474.78, 'Dispatched'),
 (78, 302, 886.11, 'Confirmed'),
 (79, 567, 210.25, 'Cancelled'),
 (80, 147, 527.54, 'Dispatched'),
 (81, 995, 554.59, 'Dispatched'),
 (82, 520, 158.32, 'Cancelled'),
 (83, 420, 320.1, 'Confirmed'),
 (84, 175, 782.21, 'Dispatched'),
 (85, 583, 493.9, 'Confirmed'),
 (86, 614, 412.96, 'Dispatched'),
 (87, 831, 161.98, 'Pending'),
 (88, 107, 739.31, 'Cancelled'),
 (89, 982, 963.89, 'Cancelled'),
 (90, 13, 925.93, 'Pending'),
 (91, 767, 167.3, 'Dispatched'),
 (92, 862, 218.19, 'Cancelled'),
 (93, 984, 447.35, 'Pending'),
 (94, 92, 443.5, 'Dispatched'),
 (95, 724, 915.46, 'Confirmed'),
 (96, 534, 548.45, 'Pending'),
 (97, 148, 947.21, 'Dispatched'),
 (98, 80, 306.95, 'Pending'),
 (99, 96, 942.46, 'Cancelled'),
 (100, 51, 622.61, 'Cancelled'),
 (101, 235, 601.58, 'Dispatched'),
 (102, 177, 336.37, 'Confirmed'),
 (103, 259, 176.17, 'Dispatched'),
 (104, 175, 533.31, 'Cancelled'),
 (105, 405, 419.05, 'Dispatched'),
 (106, 539, 653.8, 'Pending'),
 (107, 105, 784.55, 'Confirmed'),
 (108, 217, 963.66, 'Pending'),
 (109, 588, 895.96, 'Dispatched'),
 (110, 412, 769.29, 'Cancelled'),
 (111, 484, 344.09, 'Dispatched'),
 (112, 358, 224.01, 'Dispatched'),
 (113, 653, 522.64, 'Dispatched'),
 (114, 153, 349.18, 'Confirmed'),
 (115, 471, 72.9, 'Pending'),
 (116, 389, 48.39, 'Pending'),
 (117, 624, 799.86, 'Dispatched'),
 (118, 315, 741.4, 'Dispatched'),
 (119, 575, 290.07, 'Cancelled'),
 (120, 558, 239.5, 'Confirmed'),
 (121, 291, 44.13, 'Cancelled'),
 (122, 887, 410.06, 'Dispatched'),
 (123, 15, 468.28, 'Cancelled'),
 (124, 412, 766.93, 'Confirmed'),
 (125, 760, 940.9, 'Cancelled'),
 (126, 884, 901.51, 'Cancelled'),
 (127, 110, 145.77, 'Confirmed'),
 (128, 767, 455.98, 'Cancelled'),
 (129, 829, 898.0, 'Dispatched'),
 (130, 112, 301.11, 'Pending'),
 (131, 225, 6.74, 'Dispatched'),
 (132, 134, 858.53, 'Dispatched'),
 (133, 877, 380.75, 'Dispatched'),
 (134, 628, 685.56, 'Pending'),
 (135, 914, 990.69, 'Pending'),
 (136, 566, 148.1, 'Cancelled'),
 (137, 5, 238.0, 'Pending'),
 (138, 37, 11.49, 'Confirmed'),
 (139, 433, 680.07, 'Pending'),
 (140, 345, 544.21, 'Confirmed'),
 (141, 414, 335.21, 'Confirmed'),
 (142, 715, 595.05, 'Confirmed'),
 (143, 219, 942.72, 'Cancelled'),
 (144, 753, 552.95, 'Pending'),
 (145, 910, 681.23, 'Confirmed'),
 (146, 412, 222.97, 'Cancelled'),
 (147, 316, 248.75, 'Pending'),
 (148, 500, 978.49, 'Cancelled'),
 (149, 258, 775.61, 'Pending'),
 (150, 703, 184.48, 'Cancelled'),
 (151, 39, 263.19, 'Pending'),
 (152, 460, 307.41, 'Cancelled'),
 (153, 222, 318.46, 'Confirmed'),
 (154, 264, 724.29, 'Dispatched'),
 (155, 676, 877.34, 'Confirmed'),
 (156, 516, 626.0, 'Cancelled'),
 (157, 705, 603.06, 'Pending'),
 (158, 787, 90.41, 'Confirmed'),
 (159, 768, 802.65, 'Cancelled'),
 (160, 939, 47.5, 'Dispatched'),
 (161, 536, 560.26, 'Dispatched'),
 (162, 883, 436.77, 'Confirmed'),
 (163, 335, 912.48, 'Dispatched'),
 (164, 868, 287.97, 'Dispatched'),
 (165, 46, 705.44, 'Dispatched'),
 (166, 887, 296.44, 'Dispatched'),
 (167, 700, 225.45, 'Dispatched'),
 (168, 449, 254.81, 'Pending'),
 (169, 314, 729.25, 'Cancelled'),
 (170, 88, 486.56, 'Pending'),
 (171, 26, 204.69, 'Dispatched'),
 (172, 819, 551.77, 'Confirmed'),
 (173, 651, 61.31, 'Confirmed'),
 (174, 597, 716.67, 'Dispatched'),
 (175, 592, 407.95, 'Confirmed'),
 (176, 156, 630.63, 'Confirmed'),
 (177, 334, 171.57, 'Cancelled'),
 (178, 822, 909.92, 'Pending'),
 (179, 296, 997.29, 'Pending'),
 (180, 842, 605.64, 'Pending'),
 (181, 566, 524.73, 'Confirmed'),
 (182, 126, 169.37, 'Dispatched'),
 (183, 572, 162.2, 'Dispatched'),
 (184, 949, 817.9, 'Confirmed'),
 (185, 837, 58.49, 'Cancelled'),
 (186, 852, 85.64, 'Pending'),
 (187, 837, 64.81, 'Confirmed'),
 (188, 347, 796.51, 'Confirmed'),
 (189, 129, 685.04, 'Pending'),
 (190, 307, 767.23, 'Confirmed'),
 (191, 245, 673.09, 'Cancelled'),
 (192, 812, 757.02, 'Cancelled'),
 (193, 777, 400.65, 'Pending'),
 (194, 58, 404.47, 'Cancelled'),
 (195, 36, 176.94, 'Pending'),
 (196, 571, 178.44, 'Pending'),
 (197, 733, 96.16, 'Dispatched'),
 (198, 808, 28.89, 'Dispatched'),
 (199, 225, 467.35, 'Dispatched'),
 (200, 517, 141.62, 'Cancelled'),
 (201, 834, 679.7, 'Confirmed'),
 (202, 847, 625.72, 'Confirmed'),
 (203, 310, 429.69, 'Cancelled'),
 (204, 121, 539.51, 'Cancelled'),
 (205, 281, 378.19, 'Confirmed'),
 (206, 827, 621.38, 'Confirmed'),
 (207, 373, 504.82, 'Confirmed'),
 (208, 291, 121.03, 'Confirmed'),
 (209, 653, 831.12, 'Cancelled'),
 (210, 544, 860.41, 'Pending'),
 (211, 490, 457.83, 'Confirmed'),
 (212, 75, 66.35, 'Pending'),
 (213, 25, 961.88, 'Cancelled'),
 (214, 675, 467.46, 'Pending'),
 (215, 758, 744.4, 'Pending'),
 (216, 962, 904.48, 'Pending'),
 (217, 317, 98.4, 'Dispatched'),
 (218, 816, 313.8, 'Cancelled'),
 (219, 172, 85.65, 'Pending'),
 (220, 185, 129.91, 'Confirmed'),
 (221, 775, 931.29, 'Confirmed'),
 (222, 507, 378.82, 'Confirmed'),
 (223, 953, 247.73, 'Cancelled'),
 (224, 999, 331.15, 'Cancelled'),
 (225, 254, 67.91, 'Pending'),
 (226, 987, 561.59, 'Pending'),
 (227, 999, 695.34, 'Cancelled'),
 (228, 946, 748.82, 'Cancelled'),
 (229, 840, 963.22, 'Confirmed'),
 (230, 536, 80.63, 'Pending'),
 (231, 799, 299.72, 'Dispatched'),
 (232, 469, 968.48, 'Pending'),
 (233, 745, 363.52, 'Pending'),
 (234, 461, 46.98, 'Confirmed'),
 (235, 365, 540.7, 'Cancelled'),
 (236, 551, 433.59, 'Pending'),
 (237, 881, 602.2, 'Dispatched'),
 (238, 974, 547.13, 'Dispatched'),
 (239, 767, 552.48, 'Pending'),
 (240, 528, 349.0, 'Pending'),
 (241, 164, 726.49, 'Dispatched'),
 (242, 430, 135.9, 'Dispatched'),
 (243, 825, 92.22, 'Cancelled'),
 (244, 607, 851.59, 'Confirmed'),
 (245, 254, 43.51, 'Pending'),
 (246, 222, 442.22, 'Cancelled'),
 (247, 662, 160.92, 'Pending'),
 (248, 626, 936.78, 'Pending'),
 (249, 234, 579.65, 'Pending'),
 (250, 96, 529.26, 'Cancelled'),
 (251, 142, 235.16, 'Cancelled'),
 (252, 231, 429.63, 'Dispatched'),
 (253, 98, 762.4, 'Confirmed'),
 (254, 621, 166.33, 'Pending'),
 (255, 366, 813.08, 'Confirmed'),
 (256, 385, 407.18, 'Pending'),
 (257, 341, 82.16, 'Confirmed'),
 (258, 97, 546.61, 'Pending'),
 (259, 180, 663.56, 'Pending'),
 (260, 893, 146.28, 'Dispatched'),
 (261, 570, 962.24, 'Cancelled'),
 (262, 756, 997.85, 'Pending'),
 (263, 222, 961.76, 'Confirmed'),
 (264, 433, 299.03, 'Cancelled'),
 (265, 40, 775.24, 'Confirmed'),
 (266, 299, 850.93, 'Pending'),
 (267, 953, 328.7, 'Pending'),
 (268, 260, 24.0, 'Pending'),
 (269, 168, 511.45, 'Dispatched'),
 (270, 91, 418.1, 'Dispatched'),
 (271, 200, 836.05, 'Pending'),
 (272, 903, 187.95, 'Confirmed'),
 (273, 496, 433.14, 'Dispatched'),
 (274, 415, 123.85, 'Confirmed'),
 (275, 380, 710.91, 'Dispatched'),
 (276, 951, 859.56, 'Dispatched'),
 (277, 607, 884.46, 'Pending'),
 (278, 633, 848.36, 'Pending'),
 (279, 766, 352.9, 'Dispatched'),
 (280, 800, 484.98, 'Pending'),
 (281, 813, 983.15, 'Dispatched'),
 (282, 183, 971.9, 'Dispatched'),
 (283, 581, 717.59, 'Pending'),
 (284, 289, 433.87, 'Cancelled'),
 (285, 222, 549.43, 'Pending'),
 (286, 239, 128.95, 'Dispatched'),
 (287, 22, 963.01, 'Confirmed'),
 (288, 101, 716.01, 'Confirmed'),
 (289, 92, 704.93, 'Dispatched'),
 (290, 169, 521.49, 'Confirmed'),
 (291, 657, 842.4, 'Pending'),
 (292, 777, 258.04, 'Cancelled'),
 (293, 771, 115.89, 'Pending'),
 (294, 924, 878.66, 'Cancelled'),
 (295, 909, 484.94, 'Cancelled'),
 (296, 297, 76.45, 'Dispatched'),
 (297, 45, 414.48, 'Dispatched'),
 (298, 176, 735.06, 'Confirmed'),
 (299, 514, 148.17, 'Pending'),
 (300, 549, 859.2, 'Pending'),
 (301, 327, 355.47, 'Confirmed'),
 (302, 202, 255.1, 'Cancelled'),
 (303, 218, 109.65, 'Confirmed'),
 (304, 142, 460.97, 'Cancelled'),
 (305, 926, 541.21, 'Dispatched'),
 (306, 925, 201.15, 'Cancelled'),
 (307, 395, 361.11, 'Confirmed'),
 (308, 693, 495.78, 'Confirmed'),
 (309, 683, 420.41, 'Confirmed'),
 (310, 845, 838.79, 'Cancelled'),
 (311, 90, 943.53, 'Pending'),
 (312, 573, 681.84, 'Confirmed'),
 (313, 402, 411.71, 'Confirmed'),
 (314, 993, 842.06, 'Dispatched'),
 (315, 723, 490.55, 'Confirmed'),
 (316, 344, 129.41, 'Cancelled'),
 (317, 74, 741.53, 'Confirmed'),
 (318, 459, 824.65, 'Cancelled'),
 (319, 957, 106.29, 'Confirmed'),
 (320, 399, 642.23, 'Cancelled'),
 (321, 669, 453.57, 'Pending'),
 (322, 779, 903.24, 'Confirmed'),
 (323, 353, 542.81, 'Pending'),
 (324, 761, 372.59, 'Cancelled'),
 (325, 129, 210.12, 'Dispatched'),
 (326, 533, 503.82, 'Confirmed'),
 (327, 901, 243.72, 'Confirmed'),
 (328, 200, 159.51, 'Dispatched'),
 (329, 65, 151.62, 'Pending'),
 (330, 569, 343.24, 'Pending'),
 (331, 240, 31.55, 'Dispatched'),
 (332, 607, 780.63, 'Cancelled'),
 (333, 702, 998.24, 'Confirmed'),
 (334, 335, 623.41, 'Confirmed'),
 (335, 136, 26.43, 'Dispatched'),
 (336, 900, 668.63, 'Pending'),
 (337, 551, 584.3, 'Cancelled'),
 (338, 327, 359.44, 'Dispatched'),
 (339, 942, 124.76, 'Confirmed'),
 (340, 888, 577.2, 'Dispatched'),
 (341, 125, 165.75, 'Dispatched'),
 (342, 862, 594.31, 'Pending'),
 (343, 983, 731.61, 'Dispatched'),
 (344, 522, 346.69, 'Dispatched'),
 (345, 929, 648.38, 'Confirmed'),
 (346, 818, 643.6, 'Dispatched'),
 (347, 761, 523.76, 'Dispatched'),
 (348, 42, 628.95, 'Confirmed'),
 (349, 311, 627.92, 'Cancelled'),
 (350, 276, 352.03, 'Pending'),
 (351, 158, 825.62, 'Pending'),
 (352, 683, 312.25, 'Confirmed'),
 (353, 151, 136.02, 'Dispatched'),
 (354, 512, 634.84, 'Dispatched'),
 (355, 166, 724.61, 'Cancelled'),
 (356, 742, 408.69, 'Pending'),
 (357, 948, 313.75, 'Cancelled'),
 (358, 33, 108.42, 'Confirmed'),
 (359, 13, 982.21, 'Cancelled'),
 (360, 58, 654.28, 'Confirmed'),
 (361, 835, 954.88, 'Cancelled'),
 (362, 26, 214.6, 'Cancelled'),
 (363, 299, 851.97, 'Pending'),
 (364, 923, 123.98, 'Dispatched'),
 (365, 798, 741.81, 'Confirmed'),
 (366, 108, 155.94, 'Cancelled'),
 (367, 605, 401.96, 'Confirmed'),
 (368, 247, 244.91, 'Confirmed'),
 (369, 701, 123.1, 'Pending'),
 (370, 508, 847.64, 'Confirmed'),
 (371, 71, 313.04, 'Cancelled'),
 (372, 983, 308.25, 'Pending'),
 (373, 698, 910.47, 'Cancelled'),
 (374, 91, 838.52, 'Cancelled'),
 (375, 568, 55.48, 'Confirmed'),
 (376, 777, 856.11, 'Pending'),
 (377, 430, 985.82, 'Pending'),
 (378, 393, 820.12, 'Confirmed'),
 (379, 730, 624.3, 'Confirmed'),
 (380, 749, 240.77, 'Dispatched'),
 (381, 117, 617.25, 'Dispatched'),
 (382, 264, 765.23, 'Cancelled'),
 (383, 228, 924.56, 'Pending'),
 (384, 438, 767.3, 'Cancelled'),
 (385, 717, 701.58, 'Dispatched'),
 (386, 904, 317.77, 'Cancelled'),
 (387, 560, 169.71, 'Dispatched'),
 (388, 278, 483.3, 'Confirmed'),
 (389, 777, 730.32, 'Dispatched'),
 (390, 129, 470.86, 'Cancelled'),
 (391, 10, 492.97, 'Confirmed'),
 (392, 612, 308.98, 'Pending'),
 (393, 144, 902.34, 'Dispatched'),
 (394, 448, 761.58, 'Cancelled'),
 (395, 250, 751.07, 'Pending'),
 (396, 309, 792.81, 'Pending'),
 (397, 81, 12.13, 'Pending'),
 (398, 588, 670.59, 'Dispatched'),
 (399, 428, 186.7, 'Pending'),
 (400, 34, 793.44, 'Dispatched'),
 (401, 897, 887.29, 'Confirmed'),
 (402, 455, 560.12, 'Cancelled'),
 (403, 551, 564.66, 'Dispatched'),
 (404, 165, 826.31, 'Cancelled'),
 (405, 772, 848.88, 'Cancelled'),
 (406, 933, 289.09, 'Dispatched'),
 (407, 87, 819.45, 'Pending'),
 (408, 161, 36.65, 'Pending'),
 (409, 45, 814.85, 'Dispatched'),
 (410, 937, 650.52, 'Dispatched'),
 (411, 948, 348.74, 'Pending'),
 (412, 146, 846.59, 'Cancelled'),
 (413, 537, 342.29, 'Cancelled'),
 (414, 876, 409.08, 'Dispatched'),
 (415, 719, 549.6, 'Cancelled'),
 (416, 903, 938.9, 'Confirmed'),
 (417, 432, 539.52, 'Cancelled'),
 (418, 801, 927.58, 'Confirmed'),
 (419, 281, 13.07, 'Dispatched'),
 (420, 12, 602.96, 'Confirmed'),
 (421, 769, 387.36, 'Dispatched'),
 (422, 945, 417.08, 'Cancelled'),
 (423, 73, 599.12, 'Confirmed'),
 (424, 78, 145.35, 'Cancelled'),
 (425, 950, 362.38, 'Pending'),
 (426, 378, 195.13, 'Dispatched'),
 (427, 575, 400.07, 'Cancelled'),
 (428, 39, 660.39, 'Cancelled'),
 (429, 624, 15.99, 'Confirmed'),
 (430, 495, 201.62, 'Confirmed'),
 (431, 36, 41.03, 'Dispatched'),
 (432, 826, 63.73, 'Dispatched'),
 (433, 559, 227.92, 'Cancelled'),
 (434, 589, 582.95, 'Dispatched'),
 (435, 532, 35.68, 'Confirmed'),
 (436, 169, 100.22, 'Cancelled'),
 (437, 188, 22.59, 'Pending'),
 (438, 448, 683.71, 'Confirmed'),
 (439, 943, 894.36, 'Confirmed'),
 (440, 677, 153.99, 'Pending'),
 (441, 363, 244.2, 'Dispatched'),
 (442, 809, 552.86, 'Cancelled'),
 (443, 450, 390.74, 'Pending'),
 (444, 396, 95.13, 'Dispatched'),
 (445, 249, 584.94, 'Pending'),
 (446, 724, 154.66, 'Pending'),
 (447, 626, 874.8, 'Dispatched'),
 (448, 641, 476.96, 'Cancelled'),
 (449, 296, 654.54, 'Cancelled'),
 (450, 886, 576.79, 'Dispatched'),
 (451, 790, 357.87, 'Pending'),
 (452, 21, 891.0, 'Dispatched'),
 (453, 178, 625.23, 'Confirmed'),
 (454, 606, 194.27, 'Pending'),
 (455, 426, 654.07, 'Pending'),
 (456, 919, 626.38, 'Confirmed'),
 (457, 155, 855.05, 'Confirmed'),
 (458, 503, 871.35, 'Pending'),
 (459, 911, 464.64, 'Confirmed'),
 (460, 100, 793.25, 'Dispatched'),
 (461, 519, 560.94, 'Cancelled'),
 (462, 47, 914.09, 'Confirmed'),
 (463, 834, 742.76, 'Confirmed'),
 (464, 875, 471.63, 'Pending'),
 (465, 555, 65.23, 'Confirmed'),
 (466, 696, 234.17, 'Pending'),
 (467, 820, 967.7, 'Dispatched'),
 (468, 440, 462.54, 'Confirmed'),
 (469, 942, 280.32, 'Cancelled'),
 (470, 288, 320.29, 'Dispatched'),
 (471, 498, 349.63, 'Cancelled'),
 (472, 404, 963.2, 'Confirmed'),
 (473, 601, 599.91, 'Pending'),
 (474, 901, 811.25, 'Dispatched'),
 (475, 579, 335.9, 'Cancelled'),
 (476, 794, 948.08, 'Cancelled'),
 (477, 190, 579.88, 'Dispatched'),
 (478, 352, 453.81, 'Pending'),
 (479, 990, 819.32, 'Pending'),
 (480, 770, 819.06, 'Confirmed'),
 (481, 891, 180.65, 'Pending'),
 (482, 465, 723.63, 'Pending'),
 (483, 514, 935.24, 'Pending'),
 (484, 100, 662.69, 'Cancelled'),
 (485, 99, 804.59, 'Cancelled'),
 (486, 72, 472.1, 'Confirmed'),
 (487, 814, 617.69, 'Confirmed'),
 (488, 321, 304.22, 'Cancelled'),
 (489, 399, 739.42, 'Pending'),
 (490, 497, 338.32, 'Cancelled'),
 (491, 657, 123.6, 'Dispatched'),
 (492, 563, 455.77, 'Confirmed'),
 (493, 726, 121.62, 'Confirmed'),
 (494, 454, 243.34, 'Dispatched'),
 (495, 653, 18.95, 'Cancelled'),
 (496, 663, 507.62, 'Dispatched'),
 (497, 746, 702.89, 'Confirmed'),
 (498, 314, 848.48, 'Cancelled'),
 (499, 705, 672.21, 'Confirmed'),
 (500, 315, 200.03, 'Cancelled'),
 (501, 940, 617.9, 'Confirmed'),
 (502, 565, 98.05, 'Confirmed'),
 (503, 51, 783.0, 'Cancelled'),
 (504, 541, 545.63, 'Pending'),
 (505, 948, 334.07, 'Cancelled'),
 (506, 566, 494.84, 'Dispatched'),
 (507, 599, 33.81, 'Cancelled'),
 (508, 996, 373.09, 'Dispatched'),
 (509, 854, 859.21, 'Dispatched'),
 (510, 570, 313.11, 'Dispatched'),
 (511, 718, 511.25, 'Cancelled'),
 (512, 669, 928.73, 'Dispatched'),
 (513, 864, 274.24, 'Dispatched'),
 (514, 886, 664.97, 'Pending'),
 (515, 446, 190.82, 'Dispatched'),
 (516, 42, 602.85, 'Pending'),
 (517, 619, 140.12, 'Confirmed'),
 (518, 864, 504.25, 'Dispatched'),
 (519, 907, 640.8, 'Cancelled'),
 (520, 178, 556.05, 'Pending'),
 (521, 334, 780.4, 'Pending'),
 (522, 978, 981.07, 'Cancelled'),
 (523, 510, 845.47, 'Pending'),
 (524, 863, 979.77, 'Dispatched'),
 (525, 994, 248.85, 'Cancelled'),
 (526, 122, 952.93, 'Cancelled'),
 (527, 851, 465.67, 'Pending'),
 (528, 58, 674.25, 'Dispatched'),
 (529, 101, 410.6, 'Dispatched'),
 (530, 424, 327.14, 'Pending'),
 (531, 91, 989.21, 'Dispatched'),
 (532, 938, 268.12, 'Cancelled'),
 (533, 755, 234.5, 'Cancelled'),
 (534, 502, 713.57, 'Pending'),
 (535, 300, 283.43, 'Dispatched'),
 (536, 386, 286.52, 'Dispatched'),
 (537, 43, 988.3, 'Dispatched'),
 (538, 932, 907.67, 'Cancelled'),
 (539, 406, 938.43, 'Pending'),
 (540, 383, 210.3, 'Pending'),
 (541, 997, 666.2, 'Cancelled'),
 (542, 38, 634.58, 'Pending'),
 (543, 633, 983.37, 'Pending'),
 (544, 288, 587.74, 'Cancelled'),
 (545, 792, 474.6, 'Dispatched'),
 (546, 79, 330.03, 'Pending'),
 (547, 470, 963.5, 'Dispatched'),
 (548, 756, 768.74, 'Pending'),
 (549, 495, 735.92, 'Confirmed'),
 (550, 102, 141.11, 'Cancelled'),
 (551, 206, 358.84, 'Confirmed'),
 (552, 1, 373.91, 'Confirmed'),
 (553, 35, 943.41, 'Pending'),
 (554, 344, 96.41, 'Cancelled'),
 (555, 602, 896.58, 'Dispatched'),
 (556, 494, 637.25, 'Dispatched'),
 (557, 68, 500.73, 'Dispatched'),
 (558, 932, 959.86, 'Dispatched'),
 (559, 797, 527.9, 'Dispatched'),
 (560, 115, 223.69, 'Pending'),
 (561, 442, 280.42, 'Pending'),
 (562, 151, 32.07, 'Cancelled'),
 (563, 420, 359.45, 'Pending'),
 (564, 949, 438.55, 'Pending'),
 (565, 68, 58.09, 'Dispatched'),
 (566, 518, 722.38, 'Cancelled'),
 (567, 280, 953.16, 'Confirmed'),
 (568, 1, 836.07, 'Confirmed'),
 (569, 16, 354.94, 'Dispatched'),
 (570, 78, 236.81, 'Cancelled'),
 (571, 31, 924.81, 'Cancelled'),
 (572, 265, 554.63, 'Cancelled'),
 (573, 850, 418.28, 'Cancelled'),
 (574, 478, 33.42, 'Dispatched'),
 (575, 600, 391.74, 'Pending'),
 (576, 281, 297.26, 'Pending'),
 (577, 304, 25.2, 'Dispatched'),
 (578, 974, 686.0, 'Dispatched'),
 (579, 504, 917.41, 'Cancelled'),
 (580, 962, 332.69, 'Cancelled'),
 (581, 601, 938.36, 'Confirmed'),
 (582, 522, 687.27, 'Pending'),
 (583, 464, 536.59, 'Dispatched'),
 (584, 899, 799.85, 'Cancelled'),
 (585, 903, 10.1, 'Dispatched'),
 (586, 917, 24.44, 'Pending'),
 (587, 857, 546.65, 'Confirmed'),
 (588, 424, 392.41, 'Cancelled'),
 (589, 803, 966.05, 'Cancelled'),
 (590, 205, 742.21, 'Cancelled'),
 (591, 742, 529.84, 'Dispatched'),
 (592, 877, 851.97, 'Dispatched'),
 (593, 836, 915.12, 'Dispatched'),
 (594, 656, 388.63, 'Dispatched'),
 (595, 717, 204.67, 'Dispatched'),
 (596, 485, 357.27, 'Pending'),
 (597, 278, 623.19, 'Confirmed'),
 (598, 917, 902.54, 'Pending'),
 (599, 371, 46.63, 'Cancelled'),
 (600, 946, 15.38, 'Cancelled'),
 (601, 801, 694.53, 'Confirmed'),

In [ ]:
# Total calculated with for loop
total_amount=0
for  order in all_orders:
    if order[3] == "Dispatched":
        total_amount+=order[2]
total_amount

In [ ]:
# Total calculated with a generator
python_total = sum(
    amount
    for _,_, amount, status in all_orders
    if status == "Dispatched"
)

python_total

650944.29

In [ ]:
# Approach B SQL:
cursor.execute("""SELECT SUM(amount_gbp) FROM ORDERS WHERE status = 'Dispatched'""")
sql_total = cursor.fetchall()
sql_total

[(650944.29,)]

# Q. 13 — Practical: Combine Small CSV Files 
BritBooks receives three small order files for one day. 
* orders_1.csv 
* orders_2.csv 
* orders_3.csv 

Each file contains: order_id,customer_name,amount_gbp

Tasks:
* Create a folder named small_order_files . 
* Create the three CSV files with one order in each. 
* Combine them into orders_2026-07-17.csv . 
* Write the header only once. 
* Print the number of combined rows.

In [ ]:
from pathlib import Path

In [ ]:
# Folder creation
new_folder_path = Path("Folder for session5/small_order_files")
new_folder_path.mkdir(exist_ok=True)

In [ ]:
# CSVs creation
columns_name = ["order_id", "customer_name", "amount_gbp"]
orders1 = [[1, "Vicky", 91.99]]
orders2 = [[2, "Alex", 45.45]]
orders3 = [[3, "Martin", 25]]

orders1_df = pd.DataFrame(orders1, columns=columns_name)
orders2_df = pd.DataFrame(orders2, columns=columns_name)
orders3_df = pd.DataFrame(orders3, columns=columns_name)

orders1_df.to_csv('Folder for session5/small_order_files/orders1.csv', index=False, encoding='utf-8')
orders2_df.to_csv('Folder for session5/small_order_files/orders2.csv', index=False, encoding='utf-8')
orders3_df.to_csv('Folder for session5/small_order_files/orders3.csv', index=False, encoding='utf-8')

In [ ]:
# CSVs read
o1_read=pd.read_csv('Folder for session5/small_order_files/orders1.csv', header=0)
o2_read=pd.read_csv('Folder for session5/small_order_files/orders2.csv', header=0)
o3_read=pd.read_csv('Folder for session5/small_order_files/orders3.csv', header=0)

pandas.DataFrame

In [ ]:
# Combine the CSVs
combined_df = pd.concat([o3_read, o2_read, o3_read])
combined_df

   order_id customer_name  amount_gbp
0         3        Martin       25.00
0         2          Alex       45.45
0         3        Martin       25.00

In [ ]:
#create combined CSV
combined_df.to_csv('Folder for session5/small_order_files/orders_2026-07-17.csv', index=False, encoding='utf-8')

# Q. 22 — Practical: Create an Avro-Style Schema File 
BritBooks sends order events between systems. 

REQUIRED FIELDS:
| Field         |  Type |
| ------------- |:-------------:|
| order_id      | string     |
| customer_id   | string    |
| amount_gbp    | double     |
| order_status  | string    |
| coupon_code   | null or string, default null| 

TASK:

* Create the schema as a Python dictionary.
* Write it to order_event_schema.json . 
* Use indentation to keep the JSON readable. 
* Read the file again. 
* Print the field names.

In [113]:
import json

In [ ]:
# Schema aspython dictionary
schema = {
    "name": "order_events",
    "type": "record",
    "fields": [
        {
            "name": "order_id", 
            "type": "string"
        },
        {
            "name": "customer_id", 
            "type": "string"
        },
        {
            "name": "amount_gbp", 
            "type": "double"
        },
        {
            "name": "order_status", 
            "type": "string"
        },
        {
            "name": "customer_id", 
            "type": "string"
        },
        {
            "name": "coupon_code", 
            "type": ["string", "null"],
            "default": None
        }
    ]
}

In [119]:
# Write schema into a json
with open("Folder for session5/order_event_schema.json", "w", encoding="utf-8") as file:
    json.dump(schema, file, indent=4)

In [ ]:
# Read the json
with open("Folder for session5/order_event_schema.json", "r", encoding="utf-8") as file:
    json_schema_file = json.load(file)

json_schema_file

{'name': 'order_events',
 'type': 'record',
 'fields': [{'name': 'order_id', 'type': 'string'},
  {'name': 'customer_id', 'type': 'string'},
  {'name': 'amount_gbp', 'type': 'double'},
  {'name': 'order_status', 'type': 'string'},
  {'name': 'customer_id', 'type': 'string'},
  {'name': 'coupon_code', 'type': ['string', 'null'], 'default': None}]}

In [ ]:
# Read the files
json_schema_fields = [field["name"] for field in json_schema_file["fields"]]
json_schema_fields

['order_id',
 'customer_id',
 'amount_gbp',
 'order_status',
 'customer_id',
 'coupon_code']

# Q. 30 — Practical: Create a Partitioned Folder Layout 
BritBooks wants to organise orders by year and month. 

_1001, 2026-06-28, £34.99_

_1002, 2026-07-02, £18.50_

_1003, 2026-07-17, £42.75_

* Create an orders_lake folder. 
* Create year=YYYY/month=MM folders from each date. 
* Write each order to an orders.csv file in the correct partition. 
* Include the CSV header. 
* Print the created file paths.

In [ ]:
from datetime import datetime
import csv

In [ ]:
# Orders lake folder creation
order_lake_path = Path("Folder for session5/order_lake")
order_lake_path.mkdir(exist_ok=True)

In [121]:
orders = [
    {"order_id": "1001", "order_date": "2026-06-28", "amount_gbp": 34.99},
    {"order_id": "1002", "order_date": "2026-07-02", "amount_gbp": 18.50},
    {"order_id": "1003", "order_date": "2026-07-17", "amount_gbp": 42.75}
]

In [ ]:
# Loop for creating directories, csv file and the data
for order in orders:
    date = datetime.strptime(order["order_date"], "%Y-%m-%d").date()
    header = order.keys()

    folderpath_year_month = (
        order_lake_path / 
        f"{date.strftime('%Y')}" /
        f"{date.strftime('%m')}" 
    )
    folderpath_year_month.mkdir(exist_ok=True, parents=True)

    csv_path = folderpath_year_month / "orders.csv"

    if csv_path.exists():
        mode = "a"
    else:
        mode = "w"

    with open(csv_path, mode , encoding="utf-8") as file:
        writer = csv.writer(file, lineterminator='\n')
        if mode=="w":
            writer.writerow(order.keys())
        writer.writerow(order.values())

In [163]:
for file_path in sorted(order_lake_path.rglob("orders.csv")):
    print(file_path)

Folder for session5\order_lake\2026\06\orders.csv
Folder for session5\order_lake\2026\07\orders.csv